### ISSUE TITLE
Doesn't start up

### ISSUE THREAD

**Issue by WaltDisneyWorld** [RyanBrew/opal#77]
Here is the error: 
module.exports = { resendHelp, updateStatus, welcomeGroup, byeGroup, checkUser }
                                             ^

ReferenceError: welcomeGroup is not defined
    at Object.<anonymous> (/home/runner/opal/helpers.js:77:46)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/opal/app.js:10:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

**Comment by WaltDisneyWorld** [comment]
?

**Comment by ryanbrwr** [comment]
That means welcomeGroup is not defined, which means you don't have a welcomeGroup function. You have to define a welcomeGroup function or delete it.
